import { StyleSheet } from 'react-native'

export const COLORS = {
  background: '#0B1019', surface: '#161F2D', text: '#F4F1EA', muted: '#A5ADBA',
  reader: '#D5D5CF', accent: '#F4AE45', bright: '#FFC36D', border: '#293241',
} as const
const sans = { fontFamily: 'InstrumentSans', color: COLORS.text }
const bold = { fontFamily: 'InstrumentSansBold', color: COLORS.text }

export const styles = StyleSheet.create({
  background: { flex: 1, backgroundColor: COLORS.background },
  safeArea: { flex: 1 },
  startupContent: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
  scroll: { flex: 1 },
  page: { width: '100%', maxWidth: 1040, alignSelf: 'center', paddingHorizontal: 24, paddingTop: 12, paddingBottom: 24 },
  readerPage: { maxWidth: 720, paddingTop: 8, paddingBottom: 32 },
  header: { flexDirection: 'row', alignItems: 'center', gap: 8, minHeight: 48 },
  readerHeader: { marginHorizontal: -8, marginBottom: 12 },
  readerHeaderTitle: { ...bold, flex: 1, textAlign: 'center', fontSize: 14 },
  wordmark: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 9 },
  brandLogo: { width: 46, height: 46, resizeMode: 'contain' },
  wordmarkText: { ...bold, fontSize: 26, letterSpacing: -1, flexShrink: 1 },
  iconButton: { width: 48, minHeight: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center' },
  settingsButton: { backgroundColor: COLORS.surface },
  pressed: { opacity: 0.7 },
  disabled: { opacity: 0.6 },
  languageTrigger: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, minHeight: 48, minWidth: 48, paddingHorizontal: 6 },
  languageValue: { ...sans, color: COLORS.muted, fontSize: 13 },
  intro: { marginVertical: 26, gap: 8 },
  title: { ...bold, fontSize: 34, lineHeight: 38, letterSpacing: -1.1 },
  copy: { ...sans, fontSize: 14, lineHeight: 21, color: COLORS.muted },
  strong: { ...bold, fontSize: 16, lineHeight: 21 },
  small: { ...sans, color: COLORS.muted, fontSize: 13, lineHeight: 19 },
  accent: { ...sans, color: COLORS.accent },
  columns: { gap: 28 },
  wideColumns: { flexDirection: 'row', gap: 32, alignItems: 'flex-start' },
  featuredColumn: { flex: 6 },
  shelfColumn: { flex: 5 },
  sectionLabel: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', gap: 12, marginBottom: 14 },
  sectionLabelText: { ...sans, color: COLORS.muted, fontSize: 13, flexShrink: 1 },
  featureCover: { overflow: 'hidden', borderRadius: 22 },
  coverCopy: { padding: 22, minHeight: 245 },
  coverTitle: { ...sans, fontSize: 29, lineHeight: 34, letterSpacing: -0.8, color: '#193D3D' },
  coverByline: { ...sans, fontSize: 12, lineHeight: 18, marginTop: 6, color: '#294C49' },
  lightCoverText: { color: COLORS.text },
  featureBookmark: { marginTop: 105 },
  onCover: { backgroundColor: '#0B1019DB' },
  progress: { marginVertical: 18, gap: 10 },
  progressLabels: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', gap: 14 },
  progressLabel: { ...bold, fontSize: 14, flexShrink: 1 },
  progressTrack: { height: 4, borderRadius: 10, backgroundColor: COLORS.border, overflow: 'hidden' },
  progressFill: { height: 4, borderRadius: 10, backgroundColor: COLORS.accent },
  primaryButton: { flexDirection: 'row', gap: 14, minHeight: 52, borderRadius: 16, paddingVertical: 14, paddingHorizontal: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: COLORS.accent },
  primaryLabel: { ...bold, fontSize: 16, textAlign: 'center', color: COLORS.background, flexShrink: 1 },
  outlineButton: { flexDirection: 'row', gap: 8, minHeight: 48, borderWidth: 1, borderColor: COLORS.border, borderRadius: 16, paddingVertical: 14, paddingHorizontal: 20, alignItems: 'center', justifyContent: 'center' },
  outlineLabel: { ...bold, fontSize: 14, textAlign: 'center', color: COLORS.muted, flexShrink: 1 },
  shelfHeading: { flexDirection: 'row', gap: 12, alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 },
  sectionTitle: { ...bold, fontSize: 20, lineHeight: 25, flexShrink: 1 },
  textButton: { minHeight: 48, paddingHorizontal: 12, paddingVertical: 8, justifyContent: 'center' },
  textButtonLabel: { ...bold, fontSize: 14, color: COLORS.accent },
  storyList: { gap: 14 },
  card: { flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.surface, borderRadius: 22, padding: 12, paddingRight: 4 },
  cardOpen: { flexDirection: 'row', alignItems: 'center', flex: 1, gap: 14, borderRadius: 18 },
  cardCover: { width: 70, height: 92, borderRadius: 22, overflow: 'hidden' },
  detailedCover: { width: 88, height: 118 },
  narrowCover: { width: 60, height: 100 },
  cardCopy: { flex: 1, gap: 6 },
  genre: { ...sans, fontSize: 12, color: COLORS.bright, letterSpacing: 0.3 },
  quote: { marginTop: 20, padding: 20, borderWidth: 1, borderColor: COLORS.border, borderRadius: 22 },
  quoteLabel: { ...sans, fontSize: 12, color: COLORS.accent },
  quoteText: { fontFamily: 'Lora', color: COLORS.text, fontSize: 21, lineHeight: 33, marginTop: 12 },
  filters: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 24 },
  filter: { backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border, borderRadius: 30, paddingVertical: 10, paddingHorizontal: 16, minHeight: 48, justifyContent: 'center' },
  selectedFilter: { backgroundColor: '#3B3832' },
  filterLabel: { ...sans, fontSize: 14 },
  emptyState: { padding: 28, backgroundColor: COLORS.surface, borderRadius: 24, alignItems: 'center', gap: 16 },
  centered: { textAlign: 'center' },
  footer: { marginTop: 30, alignItems: 'center', gap: 16 },
  feedback: { ...sans, color: COLORS.muted, fontSize: 14, lineHeight: 21, marginTop: 14, textAlign: 'center' },
  bottomNav: { flexDirection: 'row', width: '100%', maxWidth: 1040, alignSelf: 'center', minHeight: 80, paddingVertical: 12, paddingHorizontal: 4 },
  navButton: { flex: 1, alignItems: 'center', gap: 4, minHeight: 48 },
  navIcon: { width: 64, height: 32, borderRadius: 30, alignItems: 'center', justifyContent: 'center' },
  selectedNavIcon: { backgroundColor: '#F4AE451F' },
  navLabel: { ...bold, color: COLORS.muted, fontSize: 12, textAlign: 'center' },
  readerCover: { height: 200, borderRadius: 22, overflow: 'hidden' },
  readerBookmark: { position: 'absolute', bottom: 14, right: 14 },
  readerProgress: { marginVertical: 6 },
  chapterTitle: { fontFamily: 'Lora', color: COLORS.text, fontSize: 30, lineHeight: 38 },
  byline: { ...sans, color: COLORS.muted, fontSize: 13, lineHeight: 20, marginTop: 10, marginBottom: 26 },
  paragraph: { fontFamily: 'Lora', color: COLORS.reader, fontSize: 19, lineHeight: 35, marginBottom: 22 },
  readerActions: { marginTop: 12, gap: 12 },
  ending: { alignItems: 'center', gap: 16 },
  sheetTitle: { ...bold, fontSize: 26, lineHeight: 33 },
  modalBackdrop: { flex: 1, backgroundColor: '#00000099', justifyContent: 'flex-end' },
  backdropTarget: { ...StyleSheet.absoluteFillObject },
  sheet: { width: '100%', maxWidth: 560, maxHeight: '90%', alignSelf: 'center', backgroundColor: COLORS.surface, borderTopLeftRadius: 28, borderTopRightRadius: 28, overflow: 'hidden' },
  sheetContent: { padding: 24, paddingBottom: 32, gap: 8 },
  closeSheet: { alignSelf: 'flex-end', marginTop: -12, marginRight: -12 },
  languageOption: { minHeight: 48, paddingVertical: 12, flexDirection: 'row', justifyContent: 'space-between', gap: 16 },
  edition: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 20, paddingVertical: 20, marginTop: 12 },
  editionCopy: { flex: 1, gap: 4 },
  samples: { borderTopWidth: 1, borderTopColor: COLORS.border, paddingTop: 14, paddingBottom: 20, gap: 8 },
})
